# Generated by Django 5.1.1 on 2024-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(blank=True, upload_to='long_videos/')),
                ('outsource_url', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('None', 'None'), ('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Processed', 'Processed')], default='None', max_length=20)),
            ],
        ),
    ]
