# Generated by Django 5.1.1 on 2024-09-18 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longvideos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longvideo',
            name='frontend_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
